apiVersion: apps/v1
kind: Deployment
metadata:
  name: adventure-race-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adventure-race-api
  template:
    metadata:
      labels:
        app: adventure-race-api
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: adventure-race-api
          image: ehsanadventureregistry.azurecr.io/adventure-race-platform:c9455f93b7a4b40f12daee1ee77879fa9789a35d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
